### ISSUE TITLE
The license is not defined clear enough 

### ISSUE THREAD

**Issue by it-praktyk** [PyratLabs/ansible-role-awscli#1]
Hi

I would like to emphasize that I appreciate your work - I've checked some of your Ansible roles and I like them.

I would like to use them, and maybe contribute too, but the currently defined license - like mentioned in the README.md file - is not clear enough.

Can you?
- declare which exactly version of the license BSD license you selected - https://en.wikipedia.org/wiki/BSD_licenses
- include the file LICENSE.txt or LICENSE.md in the repository like proposed [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license) 

Thank you.

**Comment by xanmanning** [comment]
Done, thanks for reporting.

https://github.com/PyratLabs/ansible-role-awscli/blob/master/LICENSE.txt

**Comment by it-praktyk** [comment]
Thx
